blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Q & A
    url: https://github.com/openbuildxyz/Web3-Frontend-Bootcamp/discussions/categories/q-a
    about: æœ‰é—®é¢˜ï¼Œåˆ° Discussions ä¸­æé—®ï¼Œå°†ä¼šæœ‰çƒ­å¿ƒç½‘å‹ç­”ç–‘ã€‚
